### ISSUE TITLE
Packery displaying two columns instead of 3

### ISSUE THREAD

**Issue by katawura** [metafizzy/packery#318]
l have set the widht to 33.33333% so that there is 3 items in a row. But this doesn's seem to be the case. Please can you advise further pleae?

**Comment by desandro** [comment]
`gutter: 10` means that 10px of gutter space needs to be accounted for in your item with. Try setting

``` css
#container .item {
  width: calc( (100% - 20px) / 3 );
}
```

**Comment by katawura** [comment]
That works fine thanks. But having issues with items. any fix for smoothly loading it all?

**Comment by katawura** [comment]
l currently got something like this 

$(document).ready(function () {

// initialize Packery
var $container = $container.packery({...});
// layout Packery after all images have loaded
$container.imagesLoaded( function() {
  $container.packery();
});
});

to initialise the itms however l get soemthing smilar to flash of unstyled content.

**Comment by desandro** [comment]
Here's one way to address FOUC and imagesLoaded. See demo http://codepen.io/desandro/pen/qbdeyY

``` css
.grid {
  /* hide by default */
  visibility: hidden;
  opacity: 0;
  transition: opacity 0.4s;
}

.grid.is-img-loaded {
  visibility: visible;
  opacity: 1;
}
```

``` js
var $grid = $('.grid').imagesLoaded( function() {
  $grid.addClass('is-img-loaded');
  $grid.packery({
    itemSelector: '.grid-item',
    percentPosition: true
  }); 
});
```
