### ISSUE TITLE
Gaps being left in layout

### ISSUE THREAD

**Issue by helloworlder** [metafizzy/packery#398]
JSFiddle below: I don't understand why I can't fit 2 green rectangles into one row. Am I doing something wrong in code, or is this a bug?  If it is a bug, is there a workaround? Otherwise is it possible to achieve what I'm after?
 
There is more than enough space for 2 green rectangles to fit, yet it won't snap in.

**Test case:** https://jsfiddle.net/dx3eovmn/2/

UPDATE: I have a test case where I remove the grid sizer. Now 2 green rectangles can sometimes fit next to each other - but not always), and there are large gaps between the pinks ones, if you play around with it a little bit: https://jsfiddle.net/dx3eovmn/3/

**Comment by desandro** [comment]
Looks like we need a better `columnWidth` that can accommodate items with about 50% width and 33.3% width. If `columnWidth` is set to `33.3%` width, then 50% width items are rounded up to take up 66%. Also, there's the issue of mixing pixel and percent values, with gutter. We may be able to address this by using `calc()` values for width.

``` css
// 6 columns with 5 15px gutters
.grid-sizer,
.grid-item {
    width: calc( ( 100% - 15px * 5 ) / 6 );
}

.grid-item--width2 {
    width: calc( ( 100% - 15px * 5 ) / 3 + 15px );
}
```

See demo https://jsfiddle.net/dx3eovmn/8/
